import React from "react";
import { useState } from "react";
import Header from "./Header";
import ErrorDisplay from "./ErrorDisplay";
import { backend_url } from "../config";
import { useNavigate } from "react-router-dom";

function Disclaimer() {
  const [error, setError] = useState("");
  const navigate = useNavigate();

  const handleprofileClick = async () => {
      try {
        const response = await fetch(`${backend_url}/profile`, {
          method: "GET",
          credentials: "include", // Important for cookies
        });
        if (response.ok) {
          //if user logged in
          navigate("/profile");
        } else {
          // Handle error from backend
          if (response.status === 401 || response.status === 404) {
            setError("login to access profile");
            // Clear error after 3 seconds
            setTimeout(() => setError(""), 3000);
          }
        }
      } catch {
        setError("Network error. Please check if the server is running.");
        setTimeout(() => setError(""), 3000);
      }
    };
  
    const handlenotificationsClick = async () => {
      try {
        const response = await fetch(`${backend_url}/notifications`, {
          method: "GET",
          credentials: "include", // Important for cookies
        });
        if (response.ok) {
          //if user logged in
          navigate("/notifications");
        } else {
          // Handle error from backend
          if (response.status === 401 || response.status === 404) {
            setError("login to access notifications");
            // Clear error after 3 seconds
            setTimeout(() => setError(""), 3000);
          }
        }
      } catch {
        setError("Network error. Please check if the server is running.");
        setTimeout(() => setError(""), 3000);
      }
    };
  

  return (
    <div
      className="bg-[#f6f7f8] dark:bg-[#0d171b] text-[#0d171b] dark:text-white min-h-screen flex flex-col"
      style={{ fontFamily: "Manrope, sans-serif" }}
    >
      {error && <ErrorDisplay message={error} onClose={() => setError(null)} />}
      
      <Header
        onProfileClick={handleprofileClick}
        onNotificationsClick={handlenotificationsClick}
      />
      <main className="grow">
        <div className="max-w-7xl mx-auto mt-10 mb-10 text-center p-6 rounded-lg bg-[#0d171b] border border-[#4c5f8e]">
          <h3 className="text-3xl font-bold text-[#0d171b] dark:text-white mb-10">
            Portfolio Analysis Features:
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-10">
            {[
              {
                title: "Prediction Methodology",
                points:[
                  "Uses technical indicators such as RSI, MACD, volatility, SMA20, SMA50, and recent returns.",
"Prediction is generated by a machine learning model trained on historical market data."],
                icon: "show_chart",
                color: "amber",
              },
              {
                title: "Model Assumptions",
                points: ["Historical market behavior contains useful signals for future risk.",
"Market conditions remain reasonably similar to training data.",
"Technical indicators reflect investor sentiment and momentum."],
                icon: "show_chart",
                color: "amber",
              },
              {
                title: "Model Limitations",
                points: ["Does not consider news, earnings reports, analyst ratings, or macroeconomic events.",
"Cannot predict unexpected market shocks.",
"Accuracy may vary across stocks and market conditions."],
                icon: "lightbulb",
                color: "green",
              },
              {
                title: "Disclaimer",
                points: ["This prediction is provided for educational and informational purposes only.",
"It should not be considered financial or investment advice.",
"Always perform your own research before making investment decisions."],
                icon: "lightbulb",
                color: "green",
              },
            ].map((item) => (
              <div
                key={item.title}
                className="bg-slate-50 dark:bg-slate-800/50 p-6 rounded-xl ring-1 ring-slate-200 dark:ring-slate-700"
              >
                <div className="flex items-center gap-4 mb-4">
                  <div
                    className={`flex h-11 w-11 items-center justify-center rounded-xl bg-${item.color}-500/15 text-${item.color}-500`}
                  >
                    <span className="material-symbols-outlined text-2xl">
                      {item.icon}
                    </span>
                  </div>
                  <h4 className="text-lg font-bold text-[#0d171b] dark:text-white">
                    {item.title}
                  </h4>
                </div>
                <div className="text-left">
                  {item.points.map((point,index) => (
                    <p key={point} className="text-sm text-slate-600 dark:text-slate-300 mb-2">
                       <span>{index+1+". "}</span> 
                      {point}
                    </p>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
export default Disclaimer;
